#!/bin/bash
source /usr/bin/entrypoint

if [[ "${REGISTRY_SKIP_CHOWN}" != "true" ]]
then
  echo "> chown data files"
  find /var/lib/registry \( \! -user registry -o \! -group registry \) -print0 | xargs -0 -r chown registry:registry
fi

if [[ -n "${REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE}" ]]
then
  chgrp registry ${REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE}
  chmod 640 ${REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE}
fi
