FROM ghcr.io/dockhippie/golang:1.21-arm@sha256:cb32a624b4989e019fec970b505fefc66b4f0608c1942637b40e1248aeefb6bf AS build

RUN git clone -b main https://github.com/distribution/distribution.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install ./cmd/...

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:91cb9847983df817454ebde7ae6ed2eeca6234cf425d3d62cf1cba4dc731557c

VOLUME ["/var/lib/registry"]
EXPOSE 5000

WORKDIR /var/lib/registry
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/registry && \
  groupadd -g 1000 registry && \
  useradd -u 1000 -d /var/lib/registry -g registry -s /bin/bash -M registry && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/digest /usr/bin/digest
COPY --from=build /srv/app/bin/registry-api-descriptor-template /usr/bin/registry-api-descriptor-template
COPY --from=build /srv/app/bin/registry /usr/bin/registry
COPY ./overlay /
