FROM ghcr.io/dockhippie/golang:1.23-arm64@sha256:6bb16543a64bf5363b10f46f2fd747a34a0a47a8fde10b4f595f4d0b170f0c37 AS build

RUN git clone -b main https://github.com/distribution/distribution.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install ./cmd/...

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:2f93d18e91936479026e0859a2c57aa138fc66595bcb35e0b4af732c1d8f5222

VOLUME ["/var/lib/registry"]
EXPOSE 5000

WORKDIR /var/lib/registry
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/registry && \
  groupadd -g 1000 registry && \
  useradd -u 1000 -d /var/lib/registry -g registry -s /bin/bash -M registry && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/digest /usr/bin/digest
COPY --from=build /srv/app/bin/registry-api-descriptor-template /usr/bin/registry-api-descriptor-template
COPY --from=build /srv/app/bin/registry /usr/bin/registry
COPY ./overlay /
