FROM webhippie/golang:1.17-arm64@sha256:8b24a5d96374c9adf5635a1e2246fa9459b36339158eafc656c32754152512c5 as build

RUN git clone -b main https://github.com/distribution/distribution.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install ./cmd/...

FROM webhippie/alpine:latest-arm64@sha256:19a529053842c6b83ff4f45fe0c4639f01c8f4e1a7af10f3b5ac9b8e627b4037

VOLUME ["/var/lib/registry"]
EXPOSE 5000

WORKDIR /var/lib/registry
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/registry && \
  groupadd -g 1000 registry && \
  useradd -u 1000 -d /var/lib/registry -g registry -s /bin/bash -M registry && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/digest /usr/bin/digest
COPY --from=build /srv/app/bin/registry-api-descriptor-template /usr/bin/registry-api-descriptor-template
COPY --from=build /srv/app/bin/registry /usr/bin/registry
COPY ./overlay /
