FROM ghcr.io/dockhippie/golang:1.25-arm64@sha256:2873685fdc0a35bedb0912ed392b807838aa6a2b9c91c3ec319353c8d6ec5b6f AS build

RUN git clone -b main https://github.com/distribution/distribution.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install ./cmd/...

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:93fa8c66b9e98f9848a60760bb5f1afabbe3ad545e400aff4e3d8c9f3bbe21e4

VOLUME ["/var/lib/registry"]
EXPOSE 5000

WORKDIR /var/lib/registry
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/registry && \
  groupadd -g 1000 registry && \
  useradd -u 1000 -d /var/lib/registry -g registry -s /bin/bash -M registry && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/digest /usr/bin/digest
COPY --from=build /srv/app/bin/registry-api-descriptor-template /usr/bin/registry-api-descriptor-template
COPY --from=build /srv/app/bin/registry /usr/bin/registry
COPY ./overlay /
