FROM webhippie/golang:1.16-amd64@sha256:d78687688797e5232d426cd6690947f8cddc903c2e8427130dd31ccbad7c12b8 as build

# renovate: datasource=github-tags depName=distribution/distribution
ENV REGISTRY_VERSION=v2.7.1

RUN git clone -b ${REGISTRY_VERSION} https://github.com/distribution/distribution.git /srv/app/src/github.com/docker/distribution && \
  cd /srv/app/src/github.com/docker/distribution && \
  GO111MODULE=off go install ./cmd/...

FROM webhippie/alpine:latest-amd64@sha256:2b090e7aaf3d1a6efa75d057bee23e688879970dcd9c27314a47bf8091b5a0d3

VOLUME ["/var/lib/registry"]
EXPOSE 5000

WORKDIR /var/lib/registry
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/registry && \
  groupadd -g 1000 registry && \
  useradd -u 1000 -d /var/lib/registry -g registry -s /bin/bash -M registry && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/digest /usr/bin/digest
COPY --from=build /srv/app/bin/registry-api-descriptor-template /usr/bin/registry-api-descriptor-template
COPY --from=build /srv/app/bin/registry /usr/bin/registry
COPY ./overlay /
