FROM ghcr.io/dockhippie/golang:1.23-arm@sha256:e90c1ed2d3e1c2276c56c417c95d4a2db2d75f6e3413d3c3c9508e8628e32e0e AS build

# renovate: datasource=github-tags depName=distribution/distribution
ENV REGISTRY_VERSION=v2.7.1

RUN git clone -b ${REGISTRY_VERSION} https://github.com/distribution/distribution.git /srv/app/src/github.com/docker/distribution && \
  cd /srv/app/src/github.com/docker/distribution && \
  GO111MODULE=off go install ./cmd/...

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:640f1979f355405d87e1daf78388b35941e12f0c108530f50d70da1d8740e58e

VOLUME ["/var/lib/registry"]
EXPOSE 5000

WORKDIR /var/lib/registry
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/registry && \
  groupadd -g 1000 registry && \
  useradd -u 1000 -d /var/lib/registry -g registry -s /bin/bash -M registry && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/digest /usr/bin/digest
COPY --from=build /srv/app/bin/registry-api-descriptor-template /usr/bin/registry-api-descriptor-template
COPY --from=build /srv/app/bin/registry /usr/bin/registry
COPY ./overlay /
