FROM webhippie/golang:1.17-arm64@sha256:7aa68466ffd9533f4c856f8446ca6b92c017a95165e7ef3839baa96295d13599 as build

# renovate: datasource=github-tags depName=distribution/distribution
ENV REGISTRY_VERSION=v2.8.1

RUN git clone -b ${REGISTRY_VERSION} https://github.com/distribution/distribution.git /srv/app/src/github.com/docker/distribution && \
  cd /srv/app/src/github.com/docker/distribution && \
  GO111MODULE=off go install ./cmd/...

FROM webhippie/alpine:latest-arm64@sha256:d059dc58e0739aac431b71e85cde3fd0ebdafd6d57f51113647548c15eff5ea0

VOLUME ["/var/lib/registry"]
EXPOSE 5000

WORKDIR /var/lib/registry
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/registry && \
  groupadd -g 1000 registry && \
  useradd -u 1000 -d /var/lib/registry -g registry -s /bin/bash -M registry && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/digest /usr/bin/digest
COPY --from=build /srv/app/bin/registry-api-descriptor-template /usr/bin/registry-api-descriptor-template
COPY --from=build /srv/app/bin/registry /usr/bin/registry
COPY ./overlay /
