version: 0.1

log:
  level: debug
  accesslog:
    disabled: true
  fields:
    service: registry

storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  maintenance:
    uploadpurging:
        enabled: false
    readonly:
      enabled: false
  delete:
    enabled: true

http:
  addr: :5000
  secret: secret
  headers:
    X-Content-Type-Options: [ nosniff ]

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
