FROM ghcr.io/dockhippie/golang:1.25-arm@sha256:96e7ae6fd78f0d65e3c8fcb8093a7ac0f96c3e8633f08956354a79f1bc620b24 AS build

# renovate: datasource=github-tags depName=distribution/distribution
ENV REGISTRY_VERSION=v2.8.3

RUN git clone -b ${REGISTRY_VERSION} https://github.com/distribution/distribution.git /srv/app/src/github.com/docker/distribution && \
  cd /srv/app/src/github.com/docker/distribution && \
  GO111MODULE=off go install ./cmd/...

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:f28b526efe69cefcd3e3ea69476240b4b8433d2612b42f9f09874ba4e32b49a0

VOLUME ["/var/lib/registry"]
EXPOSE 5000

WORKDIR /var/lib/registry
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/registry && \
  groupadd -g 1000 registry && \
  useradd -u 1000 -d /var/lib/registry -g registry -s /bin/bash -M registry && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/digest /usr/bin/digest
COPY --from=build /srv/app/bin/registry-api-descriptor-template /usr/bin/registry-api-descriptor-template
COPY --from=build /srv/app/bin/registry /usr/bin/registry
COPY ./overlay /
