FROM ghcr.io/dockhippie/golang:1.23-amd64@sha256:d9710ccf25fca88e3034de9bd2bed001f8877bdb056866c783bb91139b00a4bc AS build

# renovate: datasource=github-tags depName=distribution/distribution
ENV REGISTRY_VERSION=v2.8.3

RUN git clone -b ${REGISTRY_VERSION} https://github.com/distribution/distribution.git /srv/app/src/github.com/docker/distribution && \
  cd /srv/app/src/github.com/docker/distribution && \
  GO111MODULE=off go install ./cmd/...

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:ac6f1e56db3e7329c0ecb46d36a05025519abdf2aaf29d866ce371535eec6262

VOLUME ["/var/lib/registry"]
EXPOSE 5000

WORKDIR /var/lib/registry
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/registry && \
  groupadd -g 1000 registry && \
  useradd -u 1000 -d /var/lib/registry -g registry -s /bin/bash -M registry && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/digest /usr/bin/digest
COPY --from=build /srv/app/bin/registry-api-descriptor-template /usr/bin/registry-api-descriptor-template
COPY --from=build /srv/app/bin/registry /usr/bin/registry
COPY ./overlay /
