FROM webhippie/golang:1.19-arm@sha256:4d2d11d658c5c6aad79df9b841855ef6d793307290003cfe44297e38723e6ceb as build

# renovate: datasource=github-tags depName=distribution/distribution
ENV REGISTRY_VERSION=v2.8.1

RUN git clone -b ${REGISTRY_VERSION} https://github.com/distribution/distribution.git /srv/app/src/github.com/docker/distribution && \
  cd /srv/app/src/github.com/docker/distribution && \
  GO111MODULE=off go install ./cmd/...

FROM webhippie/alpine:latest-arm@sha256:b35c7dc76584c574e5807816b8eaca3a1ddd50208e1689e5b5242983e1b01a52

VOLUME ["/var/lib/registry"]
EXPOSE 5000

WORKDIR /var/lib/registry
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/registry && \
  groupadd -g 1000 registry && \
  useradd -u 1000 -d /var/lib/registry -g registry -s /bin/bash -M registry && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/digest /usr/bin/digest
COPY --from=build /srv/app/bin/registry-api-descriptor-template /usr/bin/registry-api-descriptor-template
COPY --from=build /srv/app/bin/registry /usr/bin/registry
COPY ./overlay /
